name: Update V2Ray Subscription

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    name: Update V2Ray Subscription
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Subconverter
      run: |
        wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter_linux64.tar.gz
        chmod +x subconverter/subconverter

    - name: Create config for subconverter
      run: |
        git remote -v
        git remote add upstream https://github.com/beck-8/subs-check.git
        git remote -v
        git fetch upstream
        git checkout master
        git rebase upstream/master -X theirs || true
        git push origin master --force-with-lease
        go run . -f ./config/config.example.yaml
        ls -lh
        tree ./


    - name: Run subconverter
      run: |
        python3 -m http.server 8000 &
        HTTP_PID=$!
        echo "HTTP server started with PID $HTTP_PID"
        sleep 5
        # 启动 subconverter
        echo "Starting subconverter..."
        cd subconverter
        ./subconverter &
        sleep 10

        # 请求 subconverter 默认转成 vless 订阅（Base64）
        # curl "http://localhost:25500/sub?target=v2ray&list=all" -o /github/workspace/result.txt
        curl -v "http://127.0.0.1:25500/sub?target=v2ray&url=http://127.0.0.1:8000/sub.yaml" -o sub.txt

        # 检查是否成功
        if [ $? -ne 0 ]; then
          echo "Failed to fetch subscription"
          exit 1
        fi
        echo "Subscription fetched successfully"
        # 停止 HTTP 服务器
        kill $HTTP_PID $SUB_PID 2>/dev/null || true
        echo "HTTP server with PID $HTTP_PID stopped"
        cat sub.txt

    - name: Base64 encode
      run: |
        cat sub.txt | base64 -w 0 > ./github/workspace/sub.txt
